/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { Track } from "./global/models";
export namespace Components {
    interface AppRoot {
    }
    interface MenuToggle {
        "showing": boolean;
        "toggle": () => void;
        "toggling": () => void;
    }
    interface PageAlbums {
        "match": MatchResults;
    }
    interface PageArtists {
    }
    interface PageGenres {
    }
    interface PageHome {
    }
    interface PageNowPlaying {
    }
    interface PagePlaylists {
        "match": MatchResults;
    }
    interface PageProfile {
        "match": MatchResults;
    }
    interface PageSettings {
    }
    interface PageTracks {
        "current_track": Track;
        "match": MatchResults;
    }
    interface PlayButton {
        "paused": boolean;
        "toggle_playing": () => void;
    }
    interface PlayTrack {
        "click_handler": () => void;
        "track": Track;
    }
    interface PlayerControls {
        "pause": () => Promise<void>;
        "play": () => Promise<void>;
        "set_playlist": (tracks: Array<Track>) => Promise<void>;
        "set_track": (track: Track) => Promise<void>;
    }
    interface ProgressBar {
        "progress": number;
    }
    interface ProgressDot {
        "progress": number;
    }
    interface TrackStats {
        "track": Track;
    }
    interface VolumeDot {
        "parent": HTMLDivElement;
        "volume": number;
        "volume_handler": (volume: number) => void;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMenuToggleElement extends Components.MenuToggle, HTMLStencilElement {
    }
    var HTMLMenuToggleElement: {
        prototype: HTMLMenuToggleElement;
        new (): HTMLMenuToggleElement;
    };
    interface HTMLPageAlbumsElement extends Components.PageAlbums, HTMLStencilElement {
    }
    var HTMLPageAlbumsElement: {
        prototype: HTMLPageAlbumsElement;
        new (): HTMLPageAlbumsElement;
    };
    interface HTMLPageArtistsElement extends Components.PageArtists, HTMLStencilElement {
    }
    var HTMLPageArtistsElement: {
        prototype: HTMLPageArtistsElement;
        new (): HTMLPageArtistsElement;
    };
    interface HTMLPageGenresElement extends Components.PageGenres, HTMLStencilElement {
    }
    var HTMLPageGenresElement: {
        prototype: HTMLPageGenresElement;
        new (): HTMLPageGenresElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageNowPlayingElement extends Components.PageNowPlaying, HTMLStencilElement {
    }
    var HTMLPageNowPlayingElement: {
        prototype: HTMLPageNowPlayingElement;
        new (): HTMLPageNowPlayingElement;
    };
    interface HTMLPagePlaylistsElement extends Components.PagePlaylists, HTMLStencilElement {
    }
    var HTMLPagePlaylistsElement: {
        prototype: HTMLPagePlaylistsElement;
        new (): HTMLPagePlaylistsElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPageSettingsElement extends Components.PageSettings, HTMLStencilElement {
    }
    var HTMLPageSettingsElement: {
        prototype: HTMLPageSettingsElement;
        new (): HTMLPageSettingsElement;
    };
    interface HTMLPageTracksElement extends Components.PageTracks, HTMLStencilElement {
    }
    var HTMLPageTracksElement: {
        prototype: HTMLPageTracksElement;
        new (): HTMLPageTracksElement;
    };
    interface HTMLPlayButtonElement extends Components.PlayButton, HTMLStencilElement {
    }
    var HTMLPlayButtonElement: {
        prototype: HTMLPlayButtonElement;
        new (): HTMLPlayButtonElement;
    };
    interface HTMLPlayTrackElement extends Components.PlayTrack, HTMLStencilElement {
    }
    var HTMLPlayTrackElement: {
        prototype: HTMLPlayTrackElement;
        new (): HTMLPlayTrackElement;
    };
    interface HTMLPlayerControlsElement extends Components.PlayerControls, HTMLStencilElement {
    }
    var HTMLPlayerControlsElement: {
        prototype: HTMLPlayerControlsElement;
        new (): HTMLPlayerControlsElement;
    };
    interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {
    }
    var HTMLProgressBarElement: {
        prototype: HTMLProgressBarElement;
        new (): HTMLProgressBarElement;
    };
    interface HTMLProgressDotElement extends Components.ProgressDot, HTMLStencilElement {
    }
    var HTMLProgressDotElement: {
        prototype: HTMLProgressDotElement;
        new (): HTMLProgressDotElement;
    };
    interface HTMLTrackStatsElement extends Components.TrackStats, HTMLStencilElement {
    }
    var HTMLTrackStatsElement: {
        prototype: HTMLTrackStatsElement;
        new (): HTMLTrackStatsElement;
    };
    interface HTMLVolumeDotElement extends Components.VolumeDot, HTMLStencilElement {
    }
    var HTMLVolumeDotElement: {
        prototype: HTMLVolumeDotElement;
        new (): HTMLVolumeDotElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "menu-toggle": HTMLMenuToggleElement;
        "page-albums": HTMLPageAlbumsElement;
        "page-artists": HTMLPageArtistsElement;
        "page-genres": HTMLPageGenresElement;
        "page-home": HTMLPageHomeElement;
        "page-now-playing": HTMLPageNowPlayingElement;
        "page-playlists": HTMLPagePlaylistsElement;
        "page-profile": HTMLPageProfileElement;
        "page-settings": HTMLPageSettingsElement;
        "page-tracks": HTMLPageTracksElement;
        "play-button": HTMLPlayButtonElement;
        "play-track": HTMLPlayTrackElement;
        "player-controls": HTMLPlayerControlsElement;
        "progress-bar": HTMLProgressBarElement;
        "progress-dot": HTMLProgressDotElement;
        "track-stats": HTMLTrackStatsElement;
        "volume-dot": HTMLVolumeDotElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface MenuToggle {
        "showing"?: boolean;
        "toggle"?: () => void;
        "toggling"?: () => void;
    }
    interface PageAlbums {
        "match"?: MatchResults;
    }
    interface PageArtists {
    }
    interface PageGenres {
    }
    interface PageHome {
    }
    interface PageNowPlaying {
    }
    interface PagePlaylists {
        "match"?: MatchResults;
    }
    interface PageProfile {
        "match"?: MatchResults;
    }
    interface PageSettings {
    }
    interface PageTracks {
        "current_track"?: Track;
        "match"?: MatchResults;
    }
    interface PlayButton {
        "paused"?: boolean;
        "toggle_playing"?: () => void;
    }
    interface PlayTrack {
        "click_handler"?: () => void;
        "onPlaying_track"?: (event: CustomEvent<number>) => void;
        "track"?: Track;
    }
    interface PlayerControls {
        "onChanging_track"?: (event: CustomEvent<Track>) => void;
    }
    interface ProgressBar {
        "progress"?: number;
    }
    interface ProgressDot {
        "progress"?: number;
    }
    interface TrackStats {
        "track"?: Track;
    }
    interface VolumeDot {
        "parent"?: HTMLDivElement;
        "volume"?: number;
        "volume_handler"?: (volume: number) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "menu-toggle": MenuToggle;
        "page-albums": PageAlbums;
        "page-artists": PageArtists;
        "page-genres": PageGenres;
        "page-home": PageHome;
        "page-now-playing": PageNowPlaying;
        "page-playlists": PagePlaylists;
        "page-profile": PageProfile;
        "page-settings": PageSettings;
        "page-tracks": PageTracks;
        "play-button": PlayButton;
        "play-track": PlayTrack;
        "player-controls": PlayerControls;
        "progress-bar": ProgressBar;
        "progress-dot": ProgressDot;
        "track-stats": TrackStats;
        "volume-dot": VolumeDot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "menu-toggle": LocalJSX.MenuToggle & JSXBase.HTMLAttributes<HTMLMenuToggleElement>;
            "page-albums": LocalJSX.PageAlbums & JSXBase.HTMLAttributes<HTMLPageAlbumsElement>;
            "page-artists": LocalJSX.PageArtists & JSXBase.HTMLAttributes<HTMLPageArtistsElement>;
            "page-genres": LocalJSX.PageGenres & JSXBase.HTMLAttributes<HTMLPageGenresElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-now-playing": LocalJSX.PageNowPlaying & JSXBase.HTMLAttributes<HTMLPageNowPlayingElement>;
            "page-playlists": LocalJSX.PagePlaylists & JSXBase.HTMLAttributes<HTMLPagePlaylistsElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "page-settings": LocalJSX.PageSettings & JSXBase.HTMLAttributes<HTMLPageSettingsElement>;
            "page-tracks": LocalJSX.PageTracks & JSXBase.HTMLAttributes<HTMLPageTracksElement>;
            "play-button": LocalJSX.PlayButton & JSXBase.HTMLAttributes<HTMLPlayButtonElement>;
            "play-track": LocalJSX.PlayTrack & JSXBase.HTMLAttributes<HTMLPlayTrackElement>;
            "player-controls": LocalJSX.PlayerControls & JSXBase.HTMLAttributes<HTMLPlayerControlsElement>;
            "progress-bar": LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
            "progress-dot": LocalJSX.ProgressDot & JSXBase.HTMLAttributes<HTMLProgressDotElement>;
            "track-stats": LocalJSX.TrackStats & JSXBase.HTMLAttributes<HTMLTrackStatsElement>;
            "volume-dot": LocalJSX.VolumeDot & JSXBase.HTMLAttributes<HTMLVolumeDotElement>;
        }
    }
}
